import { Share, View } from 'react-native';
import { useState } from 'react';
import { router } from 'expo-router';
import { Button, Eyebrow, Icon, isWeb, Meter, Panel, Row, Screen, Section, Split, Txt, usePalette } from '../../components/ui';
import { conceptCount, lessons, modules } from '../../lib/content';
import { reviewDue } from '../../lib/planner';
import { useLearning } from '../../lib/store';
export default function Progress() {
  const {state}=useLearning(),c=usePalette(),[error,setError]=useState(''),complete=lessons.filter(l=>state.lessons[l.id]?.completedAt),due=complete.filter(l=>reviewDue(state.lessons[l.id]));
  const exportBackup=async()=>{try{const text=JSON.stringify(state,null,2);if(isWeb){const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ai-learning-backup.json';a.click();URL.revokeObjectURL(url);}else await Share.share({title:'AI Learning backup',message:text});}catch{setError('Backup could not be shared. Try again.');}};
  const metrics=[{value:complete.length,total:28,label:'Experiments documented',icon:'layers-outline' as const},{value:Object.values(state.topics).filter(Boolean).length,total:conceptCount,label:'Concepts studied',icon:'bulb-outline' as const},{value:Object.keys(state.verified).length,total:modules.length,label:'Modules self-assessed',icon:'checkmark-circle-outline' as const}];
  return <Screen title="Things you can now do." subtitle="A growing collection of attempts, explanations, and small breakthroughs.">
    <Split>{metrics.map(m=><Panel key={m.label} style={{flex:1,gap:18}}><Icon name={m.icon} color={c.accent}/><View style={{flexDirection:'row',alignItems:'baseline',gap:8}}><Txt size={52} weight="600">{m.value}</Txt><Txt color={c.muted}>/ {m.total}</Txt></View><Txt size={15} weight="600">{m.label}</Txt><Meter value={m.value/m.total} label={m.label}/></Panel>)}</Split>
    <Split><Panel style={{flex:1.6}}><Section title="Field notes" aside={`${complete.length} saved`}/>{complete.length?complete.slice().reverse().map(l=><Row key={l.id} title={l.title} subtitle={state.lessons[l.id].evidence.slice(0,110)} leading={String(l.day).padStart(2,'0')} onPress={()=>router.push(`/session/${l.id}`)}/>):<View style={{gap:16,paddingVertical:24,alignItems:'flex-start'}}><Icon name="document-text-outline" color={c.accent} size={40}/><Txt size={27} weight="600">Every experiment leaves a trace.</Txt><Txt color={c.muted}>Build something small. Save what you learned. Your notes will grow into a record of what you can do.</Txt><Button title="Start the first lesson" onPress={()=>router.push('/session/D001')}/></View>}</Panel><Panel style={{flex:1}}><Eyebrow>MAKE IT STICK</Eyebrow><Section title="Recall it again" aside={`${due.length} due`}/>{due.length?due.map(l=><Row key={l.id} title={l.title} subtitle="Explain it without your notes" onPress={()=>router.push(`/session/${l.id}?review=1`)}/>):<><Txt color={c.muted} size={15}>A second look makes a lasting difference. Revisit lessons after 1, 3, 7 and 14 days.</Txt><View style={{padding:16,borderRadius:16,backgroundColor:c.soft}}><Txt size={14} weight="600" color={c.accent}>You’re all caught up.</Txt><Txt size={13} color={c.muted}>Your next review will appear here.</Txt></View></>}</Panel></Split>
    <Panel><Section title="Take your progress with you"/><Txt size={14} color={c.muted}>Export a backup before switching devices or clearing app data. Your notebook is stored locally; cloud sync is not enabled.</Txt>{!!error&&<Txt color={c.danger}>{error}</Txt>}<View style={{alignSelf:'flex-start'}}><Button title="Export progress backup" icon="share-outline" secondary onPress={()=>void exportBackup()}/></View></Panel>
  </Screen>;
}
