import {Redirect,router} from 'expo-router';
import {Platform,ScrollView,View,Pressable} from 'react-native';
import Svg,{Path,Circle,Line} from 'react-native-svg';
import {BrandMark} from '../components/brand';
import {Button,Txt,usePalette,useWide} from '../components/ui';
import {useAuth} from '../lib/auth';
function Mountain(){const c=usePalette();return <Svg width="100%" height={320} viewBox="0 0 560 320" accessibilityLabel="A path from a single grain to a mountain summit"><Path d="M0 290L70 270L120 225L165 240L255 95L295 145L355 20L470 226L560 280" stroke={c.ink} strokeWidth={1.5} fill="none"/>{[0,1,2,3,4,5,6].map(i=><Path key={i} d={`M0 ${306-i*9} Q160 ${310-i*24} 280 ${240-i*22} T560 ${300-i*8}`} stroke={c.line} strokeWidth={1} fill="none"/>)}<Line x1={355} y1={20} x2={355} y2={310} stroke={c.line} strokeDasharray="3 6"/><Circle cx={355} cy={20} r={5} fill={c.ink}/><Circle cx={70} cy={270} r={4} fill={c.ink}/></Svg>;}
export default function Product(){
 const c=usePalette(),wide=useWide(),{session}=useAuth();
 if(Platform.OS!=='web')return <Redirect href="/today"/>;
 return <ScrollView style={{flex:1,backgroundColor:c.bg}} contentContainerStyle={{paddingHorizontal:wide?56:24,paddingTop:28,paddingBottom:40,gap:wide?96:56,maxWidth:1400,width:'100%',alignSelf:'center'}}>
  <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}>
   <View style={{flexDirection:'row',alignItems:'center',gap:12}}><BrandMark size={36} color={c.ink}/><View><Txt size={16} weight="700">GRAIN / MOUNTAIN</Txt><Txt size={11} color={c.muted}>AI ENGINEERING, ONE STEP AT A TIME</Txt></View></View>
   <View style={{flexDirection:'row',gap:20,alignItems:'center'}}><Pressable accessibilityRole="link" onPress={()=>router.push('/download')} style={{paddingVertical:12}}><Txt size={14}>Get the app</Txt></Pressable><Button title={session?'Your account':'Sign in'} secondary onPress={()=>router.push('/account')}/></View>
  </View>
  <View style={{flexDirection:wide?'row':'column',gap:48,alignItems:wide?'center':'stretch'}}>
   <View style={{flex:wide?1:undefined,gap:28}}><Txt size={12} color={c.muted} style={{letterSpacing:2}}>FROM YOUR FIRST LINE TO YOUR NEXT BIG IDEA</Txt><Txt size={wide?84:54} weight="700" accessibilityRole="header">Small steps.{`\n`}Serious depth.</Txt><Txt size={20} color={c.muted} style={{maxWidth:470}}>An entire AI ecosystem. One clear next step. Learn the foundations, build real things, and keep a notebook of what you understand.</Txt><View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}><Button title="Open learning app" icon="arrow-forward" onPress={()=>router.push('/today')}/><Button title="Get the mobile app" secondary onPress={()=>router.push('/download')}/></View><Txt size={13} color={c.muted}>Free learning resources. Your pace. No race to finish.</Txt></View>
   <View style={{flex:wide?1:undefined,gap:20}}><Mountain/><View style={{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderColor:c.line,paddingTop:18}}><Txt size={12} color={c.muted}>01 / BEGIN WITH A GRAIN</Txt><Txt size={12} color={c.muted}>∞ / KEEP CLIMBING</Txt></View></View>
  </View>
  <View style={{borderWidth:1,borderColor:c.line,borderRadius:28,overflow:'hidden',backgroundColor:c.surface,flexDirection:wide?'row':'column'}}>
   <View style={{padding:wide?40:24,flex:wide?1:undefined,gap:22}}><Txt size={12} color={c.muted} style={{letterSpacing:2}}>THE PRODUCT / YOUR LEARNING WORKSPACE</Txt><Txt size={wide?40:32} weight="600">Less collecting.{`\n`}More understanding.</Txt><Txt color={c.muted}>Your next lesson, the right course, a small build, and a moment to explain it in your own words. Everything has a place.</Txt><Button title="Explore the learning path" secondary onPress={()=>router.push('/path')}/></View>
   <View style={{padding:wide?40:24,flex:wide?1:undefined,gap:18,backgroundColor:c.hero}}><Txt size={12} color={c.muted}>A LOOK INSIDE · DAY 01</Txt><Txt size={27} weight="600">Your first program.</Txt><View style={{flexDirection:'row',gap:8}}>{['Watch','Build','Recall'].map((s,i)=><View key={s} style={{flex:1,padding:14,borderRadius:16,borderWidth:1,borderColor:c.line}}><Txt size={12} color={c.muted}>0{i+1}</Txt><Txt size={14} weight="600">{s}</Txt></View>)}</View><Txt color={c.muted}>Harvard CS50P · Functions and variables</Txt><View style={{borderLeftWidth:2,borderColor:c.ink,paddingLeft:18,gap:6}}><Txt size={15}>20 minutes. One line of Python.</Txt><Txt size={13} color={c.muted}>Run print(&quot;Hello&quot;). Change it. Explain it.</Txt></View></View>
  </View>
  <View style={{gap:32}}><Txt size={wide?40:30} weight="600">A path that grows with you.</Txt><View style={{flexDirection:wide?'row':'column',gap:24}}>{[['01','Foundations','Python, engineering tools and the mathematics behind the models.'],['02','Build understanding','Machine learning, neural networks and the experiments that make them click.'],['03','Make it useful','Retrieval, agents, evaluation and deployment. Then go deep in one specialty.']].map(([n,title,body])=><View key={n} style={{flex:wide?1:undefined,gap:12,borderTopWidth:1,borderColor:c.line,paddingTop:22}}><Txt size={12} color={c.muted}>{n}</Txt><Txt size={23} weight="600">{title}</Txt><Txt size={16} color={c.muted}>{body}</Txt></View>)}</View></View>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:40,borderTopWidth:1,borderBottomWidth:1,borderColor:c.line,paddingVertical:32}}>{[['21','ordered modules'],['740','concept checkpoints'],['28','guided first steps']].map(([n,label])=><View key={n} style={{flexGrow:1,gap:4}}><Txt size={46} weight="600">{n}</Txt><Txt size={14} color={c.muted}>{label}</Txt></View>)}</View>
  <View style={{gap:16,alignItems:'flex-start'}}><Txt size={wide?46:34} weight="600">Start where you are.</Txt><Txt color={c.muted}>Keep a local notebook now. Account sync is being connected for web and future mobile builds.</Txt><Button title="Open learning app" icon="arrow-forward" onPress={()=>router.push('/today')}/></View>
  <View style={{borderTopWidth:1,borderColor:c.line,paddingTop:24,flexDirection:'row',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><Txt size={12} color={c.muted}>GRAIN / MOUNTAIN · BUILT FOR THE LONG CLIMB</Txt><Pressable accessibilityRole="link" onPress={()=>router.push('/privacy')} style={{minHeight:44}}><Txt size={13}>Privacy & your data</Txt></Pressable></View>
 </ScrollView>;
}
