const base = process.env.PREVIEW_URL ?? 'http://127.0.0.1:8090';
import { chromium } from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 402, height: 874 }, deviceScaleFactor: 2 });
page.setDefaultTimeout(60000);
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto((base + '/today'), { waitUntil: 'domcontentloaded', timeout: 180000 });
await page.getByTestId('open-lesson').waitFor({ timeout: 60000 });
fs.mkdirSync('design/shots/app', {recursive:true});
await page.screenshot({path:'design/shots/app/today.png'});
await page.getByTestId('open-lesson').click();
await page.getByLabel('Lesson evidence').waitFor();
assert.equal(await page.getByTestId('complete-lesson').isDisabled(),true);
const checks=page.getByRole('checkbox');
assert.equal(await checks.count(),3);
for(let i=0;i<3;i++){await checks.nth(i).click();await page.waitForFunction(i=>JSON.parse(localStorage.getItem('ai-learning-v1')).lessons.D001.tasks[i],i);}
assert.equal(await page.getByTestId('complete-lesson').isDisabled(),true);
await page.getByLabel('Lesson evidence').fill('I ran hello.py in the terminal. The program printed its output.');
await page.getByTestId('complete-lesson').click();
await page.getByText('Work saved. You built another piece.').waitFor();
await page.screenshot({path:'design/shots/app/lesson-completed.png'});
await page.reload({waitUntil:'domcontentloaded'});
assert.match(await page.getByLabel('Lesson evidence').inputValue(),/hello.py/);
await page.getByRole('button',{name:'Open next lesson',exact:true}).click();
await page.getByRole('heading',{name:'Variables and strings',exact:true}).waitFor();
await page.goto((base + '/session/D003'),{waitUntil:'domcontentloaded'});
assert.equal(await page.getByRole('checkbox').first().isDisabled(),true);
await page.goto((base + '/path'),{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:/Computer and learning foundations/}).waitFor();
await page.screenshot({path:'design/shots/app/path.png'});
await page.getByRole('button',{name:/Computer and learning foundations/}).click();
await page.getByRole('checkbox',{name:'hardware/software',exact:true}).click();
await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ai-learning-v1')).topics['M00.01.01']);
await page.goto((base + '/library'),{waitUntil:'domcontentloaded'});
await page.getByLabel('Search resources').fill('CampusX');
assert.equal(await page.getByText('CampusX · 100 Days of Machine Learning',{exact:true}).count(),1);
await page.screenshot({path:'design/shots/app/library.png'});
await page.getByLabel('Search resources').fill('Karpathy');
await page.getByText('Andrej Karpathy · Neural Networks: Zero to Hero',{exact:true}).waitFor();
await page.getByLabel('Search resources').fill('Reflexion');
await page.getByText('Reflexion: Language Agents with Verbal Reinforcement Learning',{exact:true}).waitFor();
await page.goto((base + '/settings'),{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:'Dark',exact:true}).click();
await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ai-learning-v1')).settings.theme==='dark');
await page.screenshot({path:'design/shots/app/settings.png'});
await page.getByLabel('Reminder times').fill('99:99');
await page.getByRole('button',{name:'Save reminder preferences',exact:true}).click();
await page.getByText('Use 1–4 times in HH:MM format and select at least one study day.').waitFor();
await page.getByLabel('Backup JSON').fill('{"version":99}');
await page.getByRole('button',{name:'Review import',exact:true}).click();
await page.getByRole('button',{name:'Replace notebook',exact:true}).click();
await page.getByText(/Import failed/).waitFor();
assert.equal(await page.evaluate(()=>!!JSON.parse(localStorage.getItem('ai-learning-v1')).lessons.D001.completedAt),true);
await page.goto((base + '/progress'),{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:'Export progress backup',exact:true}).waitFor();
await page.screenshot({path:'design/shots/app/progress.png'});
const download=page.waitForEvent('download'); await page.getByRole('button',{name:'Export progress backup',exact:true}).click();
const file=await download; assert.equal(file.suggestedFilename(),'ai-learning-backup.json');
await file.saveAs('design/shots/app/test-backup.json');
const exported=JSON.parse(fs.readFileSync('design/shots/app/test-backup.json')); assert.equal(exported.lessons.D001.tasks.every(Boolean),true);
await page.goto((base + '/settings'),{waitUntil:'domcontentloaded'});
await page.getByLabel('Backup JSON').fill(JSON.stringify(exported));
await page.getByRole('button',{name:'Review import',exact:true}).click();
await page.getByRole('button',{name:'Replace notebook',exact:true}).click();
await page.getByText('Notebook restored.',{exact:true}).waitFor();
await page.reload({waitUntil:'domcontentloaded'});
await page.getByLabel('Backup JSON').waitFor();
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ai-learning-v1')).settings.reminders),false);
assert.match(await page.evaluate(()=>JSON.parse(localStorage.getItem('ai-learning-v1')).lessons.D001.evidence),/hello.py/);
await page.goto((base + '/today'),{waitUntil:'domcontentloaded'});await page.getByTestId('open-lesson').waitFor();await page.screenshot({path:'design/shots/app/today-dark.png'});
await page.setViewportSize({width:375,height:667});await page.screenshot({path:'design/shots/app/today-small.png'});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth); assert.equal(overflow,false);
assert.deepEqual(errors,[]);
console.log('PASS: task/evidence gate, completion, reload persistence, next lesson, prerequisite preview, topic state, library search, dark theme, invalid settings/import preservation, backup export, small-phone width.');
await browser.close();

