const base = process.env.PREVIEW_URL ?? 'http://127.0.0.1:8090';
import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1200,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto((base + '/library'));
const books=page.getByRole('button',{name:'Books',exact:true});await books.waitFor();
await page.waitForTimeout(400);
const initialSelection=await page.getByTestId('sliding-selection').first().evaluate(el=>getComputedStyle(el).transform);
await books.hover();await page.mouse.down();await page.waitForTimeout(100);
const pressed=await books.evaluate(el=>new DOMMatrixReadOnly(getComputedStyle(el).transform).a);
assert.ok(pressed<0.999,'Button should shrink while pressed');
await page.mouse.up();await page.waitForTimeout(500);
assert.notEqual(await page.getByTestId('sliding-selection').first().evaluate(el=>getComputedStyle(el).transform),initialSelection,'Filter selection should slide to Books');
assert.equal(await page.getByText('A guided way in.',{exact:true}).count(),0,'Books filter should exclude course cards');
await page.getByRole('button',{name:'All',exact:true}).click();
const more=page.getByRole('button',{name:/Show details for/}).first();await more.click();
await page.getByRole('button',{name:/Hide details for/}).first().waitFor();
await page.getByRole('tab',{name:'Path',exact:true}).click();
await page.getByRole('button',{name:'Chapter 3: Build AI systems',exact:true}).click();
await page.getByRole('button',{name:/LLM applications/}).first().waitFor();
await page.getByRole('tab',{name:'Today',exact:true}).click();
await page.waitForTimeout(400);
const watchContent=await page.locator('body').innerText();
await page.getByRole('button',{name:'Build',exact:true}).click();
await page.waitForTimeout(400);
assert.notEqual(await page.locator('body').innerText(),watchContent,'Build should show a different practice task');
assert.deepEqual(errors,[]);
await page.emulateMedia({reducedMotion:'reduce'});
await page.reload();await page.getByTestId('open-lesson').waitFor();await page.waitForTimeout(400);
const watch=page.getByRole('button',{name:'Watch',exact:true});await watch.hover();await page.mouse.down();await page.waitForTimeout(100);
const reduced=await watch.evaluate(el=>getComputedStyle(el).transform);
assert.ok(reduced==='none'||reduced==='matrix(1, 0, 0, 1, 0, 0)','Reduce Motion should suppress press and hover movement: '+reduced);
await page.mouse.up();
console.log('PASS: press response, resource disclosure, chapter switch, dock navigation, practice modes and reduced motion.');
await browser.close();
