import React, { useEffect, useState } from 'react';
import { AccessibilityInfo, Platform, Pressable, ScrollView, StyleSheet, Text, useColorScheme, useWindowDimensions, View, type TextStyle, type ViewStyle, type ColorValue } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BlurView } from 'expo-blur';
import {ArrowRight,ArrowUpRight,BookOpen,Layers,Map,Sun,ChartNoAxesColumnIncreasing,SlidersHorizontal,Check,CheckCircle2,ChevronLeft,ChevronRight,Code2,Compass,Bell,Share2,ExternalLink,Search,FileText,GraduationCap,Lightbulb,LockKeyhole,Circle,MessageCircle,PlayCircle,Plus,Minus,Timer,FlaskConical} from 'lucide-react-native';
import {BrandMark} from './brand';
import {MotionPress,Reveal,MovingProgress} from './motion';
import { router } from 'expo-router';
import { useLearning } from '../lib/store';
export const light = { bg:'#F2F2F2',surface:'#FFFFFF',ink:'#111111',muted:'#606060',line:'#D6D6D6',accent:'#151515',soft:'#E8E8E8',onAccent:'#FFFFFF',danger:'#B42335',glass:'rgba(255,255,255,.86)',hero:'#EAEAEA' };
export const dark = { bg:'#000000',surface:'#101010',ink:'#F5F5F5',muted:'#A6A6A6',line:'#333333',accent:'#F4F4F4',soft:'#202020',onAccent:'#080808',danger:'#FF8D9C',glass:'rgba(18,18,18,.90)',hero:'#141414' };
export function usePalette() { const { state } = useLearning(); const system = useColorScheme(); return (state.settings.theme === 'system' ? system : state.settings.theme) === 'dark' ? dark : light; }
export function useWide() { return useWindowDimensions().width >= 900; }
export function Txt({ children, size = 17, weight = '400', color, style, ...rest }: React.ComponentProps<typeof Text> & { size?: number; weight?: TextStyle['fontWeight']; color?: ColorValue }) {
  const c = usePalette(); return <Text {...rest} style={[{ color: color ?? c.ink, fontSize: size, fontWeight: weight, lineHeight: size * (size > 32 ? 1.12 : 1.5), letterSpacing: size > 32 ? -1.6 : size > 20 ? -.5 : -.15, fontVariant: ['tabular-nums'], ...(Platform.OS === 'web' ? { fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' } : {}) }, style]}>{children}</Text>;
}
const iconMap:Record<string,typeof ArrowRight>={'arrow-forward':ArrowRight,'arrow-up-outline':ArrowUpRight,'book-outline':BookOpen,book:BookOpen,'layers-outline':Layers,'map-outline':Map,map:Map,'sunny-outline':Sun,sunny:Sun,'stats-chart-outline':ChartNoAxesColumnIncreasing,'stats-chart':ChartNoAxesColumnIncreasing,'options-outline':SlidersHorizontal,checkmark:Check,'checkmark-circle':CheckCircle2,'checkmark-circle-outline':CheckCircle2,'chevron-back':ChevronLeft,'chevron-forward':ChevronRight,'code-slash-outline':Code2,'compass-outline':Compass,'notifications-outline':Bell,'share-outline':Share2,'open-outline':ExternalLink,'search-outline':Search,'document-text-outline':FileText,'school-outline':GraduationCap,'bulb-outline':Lightbulb,'lock-closed-outline':LockKeyhole,'ellipse-outline':Circle,'chatbubble-outline':MessageCircle,'play-circle-outline':PlayCircle,'play-outline':PlayCircle,plus:Plus,minus:Minus,timer:Timer,flask:FlaskConical};
export function Icon({name,color,size=22}:{name:string;color?:ColorValue;size?:number}) {const c=usePalette(),Glyph=iconMap[name]??Circle;return <Glyph size={size} color={typeof color==='string'?color:c.ink} strokeWidth={1.65}/>;}
export function Glass({ children, style }: { children?: React.ReactNode; style?: ViewStyle }) {
  const c=usePalette(), [reduced,setReduced]=useState(false);
  useEffect(()=> { if(Platform.OS !== 'ios') return; void AccessibilityInfo.isReduceTransparencyEnabled().then(setReduced); const sub=AccessibilityInfo.addEventListener('reduceTransparencyChanged',setReduced); return ()=>sub.remove(); },[]);
  return <View style={[{ overflow:'hidden',borderRadius:28,borderCurve:'continuous',borderWidth:1,borderColor:c.line,backgroundColor:reduced || Platform.OS==='android'?c.surface:c.glass,boxShadow:c===dark?'0 8px 32px rgba(0,0,0,0.24)':'0 8px 32px rgba(28,47,86,0.09)' },style]}>{!reduced && Platform.OS!=='android' && <BlurView tint={c===dark?'dark':'light'} intensity={60} style={StyleSheet.absoluteFill} />}{children}</View>;
}
export function Panel({children,style}:{children:React.ReactNode;style?:ViewStyle}) { const c=usePalette(); return <View style={[{backgroundColor:c.surface,borderRadius:24,borderCurve:'continuous',borderWidth:1,borderColor:c.line,padding:24,gap:16},style]}>{children}</View>; }
export function Split({children}:{children:React.ReactNode}) { const wide=useWide(); return <View style={{flexDirection:wide?'row':'column',gap:24,alignItems:'stretch'}}>{React.Children.map(children, child => { if (wide || !React.isValidElement(child)) return child; const element = child as React.ReactElement<{style?:ViewStyle}>; return React.cloneElement(element, {style:{...element.props.style,flex:undefined,flexBasis:"auto",flexGrow:0,flexShrink:0}}); })}</View>; }
export function Eyebrow({children}:{children:React.ReactNode}) { const c=usePalette(); return <Txt size={12} weight="700" color={c.accent} style={{letterSpacing:1.7}}>{children}</Txt>; }
export function Meter({value,label}:{value:number;label:string}) {const c=usePalette();return <View accessible accessibilityRole="progressbar" accessibilityLabel={label} accessibilityValue={{min:0,max:100,now:Math.round(value*100)}}><MovingProgress value={value} color={c.accent} track={c.line}/></View>;}
export function Button({title,onPress,secondary=false,disabled=false,icon,testID}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;icon?:string;testID?:string}) {
 const c=usePalette();return <MotionPress accessibilityRole="button" accessibilityLabel={title} accessibilityState={{disabled}} testID={testID} disabled={disabled} onPress={onPress} style={{minHeight:54,backgroundColor:secondary?c.soft:c.accent,borderRadius:18,borderCurve:'continuous',paddingVertical:14,paddingHorizontal:22,justifyContent:'center',alignItems:'center',flexDirection:'row',gap:12,opacity:disabled?.48:1,borderWidth:1,borderColor:secondary?c.line:'transparent'}}><Reveal identity={title} style={{flexShrink:1,flexDirection:'row',alignItems:'center',gap:10}}><Txt size={15} weight="600" color={secondary?c.accent:c.onAccent} style={{flexShrink:1,textAlign:'center'}}>{title}</Txt>{icon&&<Icon name={icon} size={19} color={secondary?c.accent:c.onAccent}/>}</Reveal></MotionPress>;
}
export function Screen({ children, title, subtitle, back = false, action = true }: { children?: React.ReactNode; title?: string; subtitle?: string; back?: boolean; action?: boolean }) {
  const c = usePalette(), wide=useWide(), insets = useSafeAreaInsets(), { loaded, error, notice, dismiss } = useLearning();
  return <View style={{ flex: 1, backgroundColor: c.bg, overflow: 'hidden' }}><ScrollView keyboardShouldPersistTaps="handled" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ paddingTop: insets.top + (wide?32:16), paddingBottom: insets.bottom + 128, paddingHorizontal: wide?40:20, width: '100%', maxWidth: back?900:1200, alignSelf: 'center', gap: wide?32:24 }}>
    <View style={styles.row}>{back ? <Glass style={{borderRadius:24}}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={() => router.canGoBack() ? router.back() : router.replace('/today')} style={[styles.iconButton,{flexDirection:'row',paddingHorizontal:16,gap:6}]}><Icon name="chevron-back" size={18} /><Txt size={14} weight="600">Back</Txt></Pressable></Glass> : <View style={{flexDirection:'row',alignItems:'center',gap:10}}><View style={{width:36,height:36,borderRadius:12,backgroundColor:c.accent,alignItems:'center',justifyContent:'center'}}><BrandMark size={25} color={c.onAccent}/></View><Txt size={17} weight="700">AI Learning</Txt>{wide && <Txt size={13} color={c.muted} style={{marginLeft:12}}>YOUR LEARNING WORKSPACE</Txt>}</View>}{action && <Glass style={{borderRadius:24}}><Pressable accessibilityRole="button" accessibilityLabel="Settings" onPress={() => router.push('/settings')} style={styles.iconButton}><Icon name="options-outline" size={21}/></Pressable></Glass>}</View>
    {!!title && <View style={{ gap: 8, maxWidth:740 }}><Txt size={wide?52:36} weight="700" accessibilityRole="header">{title}</Txt>{!!subtitle && <Txt color={c.muted} size={wide?18:16}>{subtitle}</Txt>}</View>}
    {!!error && <Pressable accessibilityRole="button" accessibilityLabel="Dismiss error" onPress={dismiss} style={{ padding: 16, borderWidth: 1, borderColor: c.danger, borderRadius: 16 }}><Txt color={c.danger}>{error}</Txt></Pressable>}
    {!!notice && <Pressable accessibilityRole="button" accessibilityLabel="Dismiss notice" onPress={dismiss} style={{ padding: 16, backgroundColor: c.soft, borderRadius: 16 }}><Txt size={14}>{notice}</Txt></Pressable>}
    {loaded ? children : <Panel><Txt>Opening your learning notebook…</Txt></Panel>}
  </ScrollView></View>;
}
export function Section({ title, aside }: { title: string; aside?: string }) { const c = usePalette(); return <View style={styles.row}><Txt style={{flexShrink:1}} size={21} weight="600" accessibilityRole="header">{title}</Txt>{aside && <Txt size={13} color={c.muted}>{aside}</Txt>}</View>; }
export function Row({ title, subtitle, leading, onPress, trailing, testID }: { title: string; subtitle?: string; leading?: string; onPress: () => void; trailing?: React.ReactNode; testID?: string }) {
  const c = usePalette(); return <Pressable accessibilityRole="button" onPress={onPress} testID={testID} style={({ pressed }) => ({ flexDirection: 'row', alignItems: 'center', gap: 16, paddingVertical: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: c.line, minHeight: 76, opacity: pressed ? .65 : 1 })}>{leading && <View style={{minWidth:40,height:40,paddingHorizontal:6,borderRadius:12,backgroundColor:c.soft,justifyContent:'center',alignItems:'center'}}><Txt size={12} weight="700" color={c.accent}>{leading}</Txt></View>}<View style={{ flex: 1, gap: 4 }}><Txt size={16} weight="600">{title}</Txt>{subtitle && <Txt size={13} color={c.muted}>{subtitle}</Txt>}</View>{trailing ?? <Icon name="chevron-forward" size={17} color={c.muted} />}</Pressable>;
}
export function Pieces({ tasks }: { tasks: boolean[]; large?: boolean }) { const c=usePalette(); return <View style={{flexDirection:'row',gap:8}}>{(['Watch','Build','Recall'] as const).map((label,i)=><View key={label} accessible accessibilityLabel={`${label} ${tasks[i]?'done':'pending'}`} style={{flex:1,gap:10,padding:14,borderRadius:16,borderWidth:1,borderColor:tasks[i]?c.accent:c.line,backgroundColor:tasks[i]?c.soft:c.surface}}><Icon name={tasks[i]?'checkmark-circle':(['play-circle-outline','code-slash-outline','chatbubble-outline'] as const)[i]} color={c.accent} size={24}/><Txt size={13} weight="600">{label}</Txt></View>)}</View>; }
export function Tag({ text, active = false, onPress }: { text: string; active?: boolean; onPress?: () => void }) { const c = usePalette(); return <MotionPress accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={{ minHeight: 44, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 22, borderWidth:1,borderColor:active?c.accent:c.line, backgroundColor: active ? c.accent : c.surface, justifyContent: 'center' }}><Txt size={14} weight="600" color={active ? c.onAccent : c.muted}>{text}</Txt></MotionPress>; }
export const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, iconButton: { minWidth: 46, minHeight: 46, alignItems: 'center', justifyContent: 'center' } });
export const inputStyle = (c: typeof light): ViewStyle & TextStyle => ({ backgroundColor: c.surface, color: c.ink, borderWidth: 1, borderColor: c.line, borderRadius: 16, padding: 16, fontSize: 17, minHeight: 54 });
export const isWeb = Platform.OS === 'web';



